# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudeignore < Formula
  desc "Sync gitignore rules to Claude Code sandbox"
  homepage "https://github.com/Claudeous/claudeignore"
  version "0.0.2-alpha"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.0.2-alpha/claudeignore_darwin_amd64.tar.gz"
      sha256 "74d42d7c1035fcedb72e0a07b2767e349a3c0335629fdc407af3759d396aec63"

      define_method(:install) do
        bin.install "claudeignore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.0.2-alpha/claudeignore_darwin_arm64.tar.gz"
      sha256 "8da5cf41097b8e655c6e43026583d329a94c75e5096fef59095613ccc7412743"

      define_method(:install) do
        bin.install "claudeignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.0.2-alpha/claudeignore_linux_amd64.tar.gz"
      sha256 "0be2534a1ee2884911c350d0df9bccbfb3207fcdc231e17630918550e0128d96"
      define_method(:install) do
        bin.install "claudeignore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.0.2-alpha/claudeignore_linux_arm64.tar.gz"
      sha256 "daed33af6a92783a9ba4c94b2c5fe2e1a8ac79e8373bf56fb8a9353fcc31985e"
      define_method(:install) do
        bin.install "claudeignore"
      end
    end
  end

  test do
    system "#{bin}/claudeignore", "version"
  end
end
