# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudeignore < Formula
  desc "Sync gitignore rules to Claude Code sandbox"
  homepage "https://github.com/Claudeous/claudeignore"
  version "0.1.2-alpha"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.1.2-alpha/claudeignore_darwin_amd64.tar.gz"
      sha256 "24ab498f1ca140c351393059d3bce9b1372da47b07d0911292d249c0c60b2610"

      define_method(:install) do
        bin.install "claudeignore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.1.2-alpha/claudeignore_darwin_arm64.tar.gz"
      sha256 "0ed3672753c99319475d0850b8e487d412533edd6549c440453b24636393cf18"

      define_method(:install) do
        bin.install "claudeignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.1.2-alpha/claudeignore_linux_amd64.tar.gz"
      sha256 "a3f21f13e6c0732e66264ee3f1d042d8fec55f592437e7e2a9eeabfcae66fcfc"
      define_method(:install) do
        bin.install "claudeignore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.1.2-alpha/claudeignore_linux_arm64.tar.gz"
      sha256 "e24c3281e9a589fb7ddf78c8be81903f5c9a4ff9ec3fb897a2781f0a6386c59f"
      define_method(:install) do
        bin.install "claudeignore"
      end
    end
  end

  test do
    system "#{bin}/claudeignore", "version"
  end
end
