# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudeignore < Formula
  desc "Sync gitignore rules to Claude Code sandbox"
  homepage "https://github.com/Claudeous/claudeignore"
  version "0.0.3-alpha"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.0.3-alpha/claudeignore_darwin_amd64.tar.gz"
      sha256 "727853fd880ee02e80a8a9ce2ae08730681eed45d93417dd46f7f9ba91bb6807"

      define_method(:install) do
        bin.install "claudeignore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.0.3-alpha/claudeignore_darwin_arm64.tar.gz"
      sha256 "259e029d222ffd7191a358c01f15e988b224777e462721a8153c4f7614cbcd25"

      define_method(:install) do
        bin.install "claudeignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.0.3-alpha/claudeignore_linux_amd64.tar.gz"
      sha256 "8153dd2f7e03cebc3a942df45e3a4f7cbc07007957ed6dac22014ed3f7a124c9"
      define_method(:install) do
        bin.install "claudeignore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Claudeous/claudeignore/releases/download/v0.0.3-alpha/claudeignore_linux_arm64.tar.gz"
      sha256 "a92d9a14f3eb99a04825a0baa2c8b0b1d320b225f4ea49d65034c91127987606"
      define_method(:install) do
        bin.install "claudeignore"
      end
    end
  end

  test do
    system "#{bin}/claudeignore", "version"
  end
end
